### ISSUE TITLE
멈춤이 안됩니다..

### ISSUE THREAD

**Issue by SooJungChae** [planet-team-7/caffeine#2]
START > || (멈춤버튼) > 딴짓하고 오니까 버그에 잡혀있네요!
멈춤 기능 확인부탁드려요~

**Comment by zzinny** [comment]
SooJung님 제보 감사합니다.
말씀해주신 버그 수정하여 1.3버전을 재배포하였습니다. 
배포에는 최대 60분이 걸릴 수 있으니 약 1시간 후에 다시 다운로드해주세요ㅎㅎ
